name: mvvm_firebase
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_auth: ^4.6.0
  firebase_core: ^2.12.0
  # get it
  get_it: ^7.6.0
  stacked: ^3.2.5
  http: ^0.13.6
  
  mockito: ^5.4.0
  firebase_auth_mocks: ^0.11.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true



analyzer:
  strong-mode: true
  language:
    enableSuperMixins: true
